apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: f9x1oag3u-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: f9x1oag3u-go 
  name: f9x1oag3u-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: f9x1oag3u-go 
